# Generated by Django 6.1 on 2026-09-23 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0001_sede_y_tipo_espacio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='cowork.sede')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='espacios', to='cowork.tipoespacio')),
            ],
            options={
                'verbose_name': 'espacio',
                'verbose_name_plural': 'espacios',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('cantidad_personas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='confirmada', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='cowork.espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.UniqueConstraint(fields=('sede', 'nombre'), name='espacio_nombre_unico_por_sede'),
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad__gte', 1)), name='espacio_capacidad_minima'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='reserva_fin_posterior_al_inicio'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_personas__gte', 1)), name='reserva_cantidad_personas_minima'),
        ),
    ]
